2025-05-27 19:02:50,122 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.6.1.161:42231'
2025-05-27 19:02:51,682 - distributed.worker - INFO -       Start worker at:     tcp://10.6.1.161:41277
2025-05-27 19:02:51,682 - distributed.worker - INFO -          Listening to:     tcp://10.6.1.161:41277
2025-05-27 19:02:51,682 - distributed.worker - INFO -           Worker name:             SLURMCluster-4
2025-05-27 19:02:51,682 - distributed.worker - INFO -          dashboard at:           10.6.1.161:36893
2025-05-27 19:02:51,682 - distributed.worker - INFO - Waiting to connect to: tcp://146.186.150.12:32801
2025-05-27 19:02:51,682 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 19:02:51,682 - distributed.worker - INFO -               Threads:                          1
2025-05-27 19:02:51,682 - distributed.worker - INFO -                Memory:                 100.00 GiB
2025-05-27 19:02:51,682 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-1ek4hzex
2025-05-27 19:02:51,682 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 19:02:51,721 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-05-27 19:02:51,722 - distributed.worker - INFO -         Registered to: tcp://146.186.150.12:32801
2025-05-27 19:02:51,722 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 19:02:51,722 - distributed.core - INFO - Starting established connection to tcp://146.186.150.12:32801
2025-05-27 20:13:41,021 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/tornado/iostream.py", line 1113, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/worker.py", line 1267, in heartbeat
    response = await retry_operation(
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 416, in retry_operation
    return await retry(
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 395, in retry
    return await coro()
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 143, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.6.1.161:49444 remote=tcp://146.186.150.12:32801>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-05-27 20:13:41,028 - distributed.core - INFO - Connection to tcp://146.186.150.12:32801 has been closed.
2025-05-27 20:13:41,028 - distributed.worker - INFO - Stopping worker at tcp://10.6.1.161:41277. Reason: worker-handle-scheduler-connection-broken
2025-05-27 20:13:41,032 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.6.1.161:42231'. Reason: worker-handle-scheduler-connection-broken
2025-05-27 20:13:41,032 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-05-27 20:13:41,037 - distributed.nanny - INFO - Worker closed
2025-05-27 20:13:43,448 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.6.1.161:42231'. Reason: nanny-close-gracefully
2025-05-27 20:13:43,448 - distributed.nanny - INFO - Nanny at 'tcp://10.6.1.161:42231' closed.
2025-05-27 20:13:43,448 - distributed.dask_worker - INFO - End worker
