2025-05-27 18:56:51,084 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.6.1.190:34945'
2025-05-27 18:56:53,441 - distributed.worker - INFO -       Start worker at:     tcp://10.6.1.190:33383
2025-05-27 18:56:53,442 - distributed.worker - INFO -          Listening to:     tcp://10.6.1.190:33383
2025-05-27 18:56:53,442 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2025-05-27 18:56:53,442 - distributed.worker - INFO -          dashboard at:           10.6.1.190:38051
2025-05-27 18:56:53,442 - distributed.worker - INFO - Waiting to connect to: tcp://146.186.150.12:37397
2025-05-27 18:56:53,442 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 18:56:53,442 - distributed.worker - INFO -               Threads:                          1
2025-05-27 18:56:53,442 - distributed.worker - INFO -                Memory:                 100.00 GiB
2025-05-27 18:56:53,442 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-n70q6yp3
2025-05-27 18:56:53,442 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 18:56:53,485 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-05-27 18:56:53,486 - distributed.worker - INFO -         Registered to: tcp://146.186.150.12:37397
2025-05-27 18:56:53,486 - distributed.worker - INFO - -------------------------------------------------
2025-05-27 18:56:53,486 - distributed.core - INFO - Starting established connection to tcp://146.186.150.12:37397
2025-05-27 19:00:08,207 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 226, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/worker.py", line 1267, in heartbeat
    response = await retry_operation(
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 416, in retry_operation
    return await retry(
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 395, in retry
    return await coro()
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 137, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.6.1.190:57478 remote=tcp://146.186.150.12:37397>: Stream is closed
2025-05-27 19:00:08,215 - distributed.core - INFO - Connection to tcp://146.186.150.12:37397 has been closed.
2025-05-27 19:00:08,215 - distributed.worker - INFO - Stopping worker at tcp://10.6.1.190:33383. Reason: worker-handle-scheduler-connection-broken
2025-05-27 19:00:08,219 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.6.1.190:34945'. Reason: worker-handle-scheduler-connection-broken
2025-05-27 19:00:08,219 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-05-27 19:00:08,221 - distributed.nanny - INFO - Worker closed
2025-05-27 19:00:12,842 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.6.1.190:34945'. Reason: nanny-close-gracefully
2025-05-27 19:00:12,843 - distributed.nanny - INFO - Nanny at 'tcp://10.6.1.190:34945' closed.
2025-05-27 19:00:12,844 - distributed.dask_worker - INFO - End worker
